import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
	{
		_id: uuid(),
		title: "The Jungle Book",
		author: "Rudyard Kipling",
		price: "5000",
		categoryName: "action",
		rating: "5",
	},
	{
		_id: uuid(),
		title: "The Three Musketeers",
		author: "Alexandre Dumas",
		price: "3000",
		categoryName: "action",
		rating: "3",
	},
	{
		_id: uuid(),
		title: " Treasure Island",
		author: "Robert Louis Stevenson",
		price: "1000",
		categoryName: "action",
		rating: "2",
	},
	{
		_id: uuid(),
		title: " Harry Potter",
		author: "J. K. Rowling",
		price: "4900",
		categoryName: "action",
		rating: "5",
	},
	{
		_id: uuid(),
		title: "  Pride and Prejudice",
		author: "Jane Austen",
		price: "1500",
		categoryName: "classic",
		rating: "4",
	},
	{
		_id: uuid(),
		title: "  To Kill a Mockingbird",
		author: "Harper Lee",
		price: "1800",
		categoryName: "classic",
		rating: "5",
	},
	{
		_id: uuid(),
		title: "  The Great Gatsby",
		author: "F. Scott Fitzgerald",
		price: "1300",
		categoryName: "classic",
		rating: "1",
	},
	{
		_id: uuid(),
		title: " Of Mice and Men",
		author: "John Steinbeck",
		price: "1900",
		categoryName: "fiction",
		rating: "3",
	},
	{
		_id: uuid(),
		title: "  Things Fall Apart",
		author: "Chinua Achebe",
		price: "1700",
		categoryName: "fiction",
		rating: "2",
	},
	{
		_id: uuid(),
		title: " The Kite Runner",
		author: "Khaled Hosseini",
		price: "1600",
		categoryName: "fiction",
		rating: "4",
	},
	{
		_id: uuid(),
		title: " The Pursuit of Love",
		author: "Nancy Mitford",
		price: "2600",
		categoryName: "romance",
		rating: "1",
	},
	{
		_id: uuid(),
		title: " The Notebook",
		author: "Nicholas Sparks",
		price: "3600",
		categoryName: "romance",
		rating: "5",
	},
	{
		_id: uuid(),
		title: " The Time Traveler’s Wife",
		author: " Audrey Niffenegger",
		price: "4600",
		categoryName: "romance",
		rating: "3",
	},
	{
		_id: uuid(),
		title: " I Bought a Little City ",
		author: " Donald Barthelme",
		price: "500",
		categoryName: "short-story",
		rating: "2",
	},
	{
		_id: uuid(),
		title: " The Night Driver ",
		author: "  Italo Calvino",
		price: "600",
		categoryName: "short-story",
		rating: "1",
	},
	{
		_id: uuid(),
		title: " The Swimmer ",
		author: "  John Cheever",
		price: "800",
		categoryName: "short-story",
		rating: "4",
	},
];
